baseurl = "http://www.example.com"
theme = [ "hugo-embed-pdf-shortcode"]
languageCode = "en-us"

[module]
[[module.imports]]
  path = "github.com/hugo-mods/icons"
[[module.imports]]
  path = 'github.com/LordMathis/hugo-theme-nightfall'
[markup.highlight]
style = "github-dark"

[params]
  author = "Allen Mao"
  user = "allen"
  hostname = "maosays"
  keywords = "blog,developer,personal"
  avatarurl = "images/bridge_chicago.jpg"
  #gravatar = "john.doe@example.com"
  since = 2023
  colorScheme = "auto"
  
  # Social links
  [[params.social]]
    key = 0
    name = "github"
    url = "https://github.com/citronella3alain/"
  [[params.social]]
    key = 1
    name = "youtube"
    url = "https://youtube.com/@allenmao8935"
  [[params.social]]
    key = 0
    name = "linkedin"
    url = "https://www.linkedin.com/in/allen-s-mao/"
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Menu links
[menu]
  [[menu.header]]
    name = "blog"
    weight = 2
    url  = "posts/"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about/"
  [[menu.header]]
    name = "cv"
    weight = 3
    url = "cv/"